Update antd and dayjs to latest (#7319)
* Update antd to latest

Some new functionality was required for FF work

* Remove unneeded ts-ignores

* Solve datepicker dayjs mismatch

> frontend/src/lib/components/DateFilter/DateFilterRange.tsx(8,48): error TS2345: Argument of type 'import("/home/macobo/backups/2/projects/posthog/node_modules/rc-picker/lib/generate/index").GenerateConfig<import("/home/macobo/backups/2/projects/posthog/node_modules/rc-picker/node_modules/dayjs/index").Dayjs>' is not assignable to parameter of type 'import("/home/macobo/backups/2/projects/posthog/node_modules/rc-picker/lib/generate/index").GenerateConfig<import("/home/macobo/backups/2/projects/posthog/node_modules/dayjs/index").Dayjs>'.

* Update dayjs - forces single version of dayjs to exist