chore(migrations): make migration 0273 test not atomic (#13215)
As a result of adding
https://github.com/PostHog/posthog/pull/13191/files#diff-f6fb7704f4500fd164ae831ebd5d4a28bb1c0d5fed6f0080c45f1a9cf28591fa
we ended up having test failures on this migration:

```
django.db.utils.OperationalError: cannot ALTER TABLE "posthog_team" because it has pending trigger events
```

Making this a non-atomic test fixes the issue.