fix(snowflake): properly escape table name
Previously we weren't wrapping the table name in quotes for the case
that there were multiple files to be uploaded to the same table. This
would cause the workflow to fail with an error like:

```
snowflake.connector.errors.ProgrammingError: 002003 (42000): SQL compilation error
```